image: maven:3.8.4-openjdk-17

default:
  tags:
    - windows

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2"

cache:
  paths:
    - .m2

stages:
  - build
  - test

build:
  stage: build
  script: mvn compile -B
  artifacts:
    paths:
      - target/

test:
  stage: test
  script: mvn test -B