#services:
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - 8080:8080
#    depends_on:
#      - db
#  db:
#    image: postgres
#    environment:
#      POSTGRES_DB: Twister
#      POSTGRES_PASSWORD: root
#      POSTGRES_USER: postgres
#    ports:
#      - '5432'
