<!DOCTYPE html>
<html lang="en">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

<style>
    body {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 80vh;
        margin: 0;
    }

</style>
<title>Twister</title>
<body>
<div class="form-gap"></div>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-4 mx-auto">
            <div class="message-window" style="border: 1px solid #ccc; background-color: #f8f9fa; padding: 20px; border-radius: 5px;">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="text-center">
                        <h3>
                            <i class="fa fa-lock fa-4x"></i>
                        </h3>
                        <div class="alert alert-danger" role="alert">
                            No Activation Code!
                        </div>
                    </div>
                </div>
            </div>
            <div class="forgot">
                <h2> No Activation Code?</h2>
                <p>Take a 3-step process:</p>
                <li><span class="text-primary text-medium">1.</span>Try to Login</li>
                <li><span class="text-primary text-medium">2.</span>Check your email for a link.</li>
                <li><span class="text-primary text-medium">3.</span>Open the link to activate account.</li>
            </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>